B/mail
kronos-et-al/MensaApp pull request #55
Opened 2023-07-24 08:04 UTC by uglrl

Make sure, you have done de following before merging this pull request:
- [ ] Your code is **documented** using doc comments.
- [ ] You added appropriate **logging** in your code.
- [ ] You added **unit tests** to all your implemented functions.
- [ ] You ran `cargo format` to format your code.
- [ ] You ran `cargo clippy` to check for improvements.
- [ ] You added the **class descriptions** of the classes you implemented in the **latex document** on overleaf.
      Make sure to mark any changes you made to the design documents specification.

2023-07-24 17:10 UTC, worldofjoni requested changes
looks good for the most part

2023-07-24 17:10 UTC, worldofjoni commented on backend/src/layer/data/mail/mail_sender.rs
> +        let image_id: &str = &Simple::from_uuid(info.image_id).to_string();
why not just `.to_string()` using hyphonated formatting?
https://docs.rs/uuid/latest/uuid/struct.Uuid.html#formatting

2023-07-24 17:10 UTC, worldofjoni commented on backend/src/layer/data/mail/mail_sender.rs
> +        Ok(template.render(&args))
i think it all would be less fo an wall of text if you created a list of pairs and then collected it into a HashMap. All these variable names (which are redundant to the keys in the hashmap) make it realy hard to read.

2023-07-24 17:10 UTC, worldofjoni commented on backend/src/layer/data/mail/mail_sender.rs
> +        Ok(template.render(&args))
maybe even a list of `(&str, &dyn ToString)`

2023-07-24 17:10 UTC, worldofjoni commented on backend/src/startup/config/mail_info.rs
> +pub struct MailInfo {
mail info struct should be placed inside mail module (in the data layer)

2023-07-24 17:21 UTC, worldofjoni commented on backend/src/layer/data/mail/mail_sender.rs
> +mod test {
consider adding a test to check that the values could be inserted into the template correctrly (and there are no wrongly named fields and so on; on whatever the library errors)

2023-07-25 06:17 UTC, worldofjoni commented on backend/src/layer/data/mail/mail_sender.rs
> +        info!("Email sent successfully!");
provide more information like an image_id

2023-07-25 08:56 UTC, uglrl commented on backend/src/layer/data/mail/mail_sender.rs
> +            .subject("An image was reported for reviewing")
An image was reported and requires your review

2023-07-25 17:08 UTC, worldofjoni approved these changes

2023-07-25 17:08 UTC, worldofjoni commented on backend/src/layer/data/mail/mail_sender.rs
> +        let expected = format!("The image at the url {}\nwith the id {}\nwas reported {} times.\nReason: {}\nImage automatically hidden: {}\n\nAdditional Data:\nPositive ratings: {}\nNegative ratings
that was not what i meant with testing the formating.
If there is no way to get an error from the template render method, you could check whether any pattern string using `{{ ...}}` (or whatever its syntax was) sill remains in the format (maybe if you missspelled an argument in the template file).
We dont want to change the test if we change the template.

2023-07-26 09:06 UTC, merged